# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Header Menu
menu:
  Home: /
  Archives: archives
  Categories: categories
  Tags: tags
  # About: 
rss: /atom.xml

since: 2020

# Set default keywords (Use a comma to separate)
keywords: ""

# Put your favicon.ico into `hexo-site/themes/hiero/source/` directory.
favicon: css/images/logo_ico.png


# Put your avatar.jpg into `hexo-site/themes/hiero/source/` directory.
# url is target link (E.g. `url: https://hexo.io/logo.svg` or `url: css/images/mylogo.jpg`)
avatar: 
  enable: true
  width: 124
  height: 124
  bottom: 10
  url: css/images/logo_title.png
  

# AboutPage background
about_big_image: [css/images/pose.jpg, https://source.unsplash.com/collection/954550/1920x1080]


# Homepage thumbnail
random_thumb: false


# Post Article's Content
post_catalog:
  enable: true

# Sidebar like in homepage, is necessary to disable [post_catalog]
post_sidebar:
  enable: false

# Content
fancybox: true


# Sidebar
sidebar: right
widgets:
- search
# - social
- recent_posts
- category
- tag
# - tagcloud
- archive

# Social Links
# Key is the name of FontAwsome icon.
# Value is the target link (E.g. GitHub: https://github.com/iTimeTraveler)
social:
  # Github: 
  # Weibo: 
  # Twitter: 
  # Facebook: 
  # Google-plus: 
  # Instagram: 
  # Pinterest: 
  # Flickr: 
  # email:


# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false


# comment ShortName, you can choose only ONE to display.
gentie_productKey: #your-gentie-product-key
duoshuo_shortname:
disqus_shortname: 
livere_shortname: MTAyMC81MDAxOC8yNjUwOQ==
uyan_uid: 
wumii:
gitment:
  owner:                   #Your GitHub ID
  repo:                    #The repo to store comments
  client_id:               #Your client ID
  client_secret:           #Your client secret
valine:
  appid: #Leancloud应用app_id，必填
  appkey: #Leancloud应用app_key，必填
  notify: false
  verify: false
  placeholder: ヾﾉ≧∀≦)o快来评论一下吧!
  avatar: 
  pageSize: 10
  visitor: true

# Code Highlight theme
# Available value:
#    default | normal | night | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
highlight_theme: default



# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive


# widget behavior
archive_type: 'monthly'
show_count: true

# Google Webmaster tools verification setting
# See: https://www.google.com/webmasters/
google_site_verification:
baidu_site_verification:
qihu_site_verification:

# Miscellaneous
google_analytics: 
gauges_analytics:
baidu_analytics:
tencent_analytics:
busuanzi_analytics: true
twitter:
google_plus:
fb_admins:
fb_app_id:

# Facebook SDK Support.
# https://github.com/iissnan/hexo-theme-next/pull/410
facebook_sdk:
  enable: false
  app_id:       #<app_id>true
  fb_admin:     #<user_id>
  like_button:  #true
  webmaster:    #true

# CNZZ count
cnzz_siteid: true

# donation button
donate:
    enable: true
    message: '如果觉得我的文章对您有用，请随意打赏。您的支持将鼓励我继续创作!'
    wechatImage: 
    alipayImage: 

# Automatic page load progress bar by PACE.js
progressBar:
  enable: true #switch
  themeCSS: https://github.com/HubSpot/pace/raw/master/themes/orange/pace-theme-flash.css    #PATH to PACE theme CSS, support relative / absolute path

# Ad
ad:
  google_adsense_ad_client_id: 

# # Live2D
# ## https://github.com/EYHN/hexo-helper-live2d
# live2d:
#   enable: true
#   # enable: false
#   scriptFrom: local # 默认
#   pluginRootPath: live2dw/ # 插件在站点上的根目录(相对路径)
#   pluginJsPath: lib/ # 脚本文件相对与插件根目录路径
#   pluginModelPath: assets/ # 模型文件相对与插件根目录路径
#   # scriptFrom: jsdelivr # jsdelivr CDN
#   # scriptFrom: unpkg # unpkg CDN
#   # scriptFrom: https://cdn.jsdelivr.net/npm/live2d-widget@3.x/lib/L2Dwidget.min.js # 你的自定义 url
#   tagMode: false # 标签模式, 是否仅替换 live2d tag标签而非插入到所有页面中
#   debug: false # 调试, 是否在控制台输出日志
#   model:
#     use: live2d-widget-model-z16 # npm-module package name
#     # use: wanko # 博客根目录/live2d_models/ 下的目录名
#     # use: ./wives/wanko # 相对于博客根目录的路径
#     # use: https://cdn.jsdelivr.net/npm/live2d-widget-model-wanko@1.0.5/assets/wanko.model.json # 你的自定义 url
#   display:
#     position: left
#     width: 150
#     height: 300
#   mobile:
#     show: false # 手机中是否展示